test: &default

  # Credentials for REST APIs
  client_id: ARbPOn02Xwrvl1PG9KQGWyaFdSneDVuIPWKOdhHE3mbKXJf6sTGUF67z43L6e2uTUCMhfqn-2uMUQ0Lu
  client_secret: EDaeVkOqGk1d3TymefMPf_CKLTRfxyzZti0KbCEywiWd0pPZZPA0g0tpnzT4wplrxZJw7bqRQYTiYulr

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: live
